# Generated by Django 3.1 on 2020-08-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_tag', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date asked')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date written')),
                ('article_tag', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qogether.question')),
            ],
        ),
    ]
