# Generated by Django 3.1 on 2020-08-25 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qogether', '0002_auto_20200823_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 14, 31, 948099, tzinfo=utc), verbose_name='date written'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 8, 14, 31, 947104, tzinfo=utc), verbose_name='date asked'),
        ),
    ]
