# Generated by Django 3.1 on 2020-08-30 02:32

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qogether', '0004_auto_20200829_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 2, 32, 32, 852036, tzinfo=utc), verbose_name='date written'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 2, 32, 32, 851037, tzinfo=utc), verbose_name='date asked'),
        ),
    ]
