# Generated by Django 3.1 on 2020-09-02 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qogether', '0005_auto_20200830_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 8, 22, 0, 451141, tzinfo=utc), verbose_name='date written'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 8, 22, 0, 451141, tzinfo=utc), verbose_name='date asked'),
        ),
    ]
