# Generated by Django 3.1 on 2020-09-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qogether', '0010_auto_20200908_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
