# Generated by Django 3.0.3 on 2020-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qogether', '0011_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
